### ISSUE TITLE
Cannot start icon-etl

### ISSUE THREAD

**Issue by iamacoderguy** [geometry-labs/icon-api#28]
Hi team,

I pulled the code and used `docker-compose up -d` to start all containers, but got a problem with icon-etl.
It couldn't start. I attach the logs as below

```
2021-06-02 15:53:48,413 - root [INFO] - Using https://ctz.solidwallet.io/api/v3
%3|1622649228.485|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#192.168.80.10:9092 failed: Connection refused (after 43ms in state CONNECT)
%3|1622649229.444|FAIL|rdkafka#producer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#192.168.80.10:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/icon-etl/__main__.py", line 25, in <module>
    cli()
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/icon-etl/iconetl/cli/stream.py", line 234, in stream
    pid_file=pid_file,
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 57, in __init__
    self.last_synced_block = read_last_synced_block(self.last_synced_block_file)
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 134, in read_last_synced_block
    return int(last_synced_block_file.read())
ValueError: invalid literal for int() with base 10: ''
2021-06-02 15:54:02,756 - root [INFO] - Using https://ctz.solidwallet.io/api/v3
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/icon-etl/__main__.py", line 25, in <module>
    cli()
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/icon-etl/iconetl/cli/stream.py", line 234, in stream
    pid_file=pid_file,
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 57, in __init__
    self.last_synced_block = read_last_synced_block(self.last_synced_block_file)
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 134, in read_last_synced_block
    return int(last_synced_block_file.read())
ValueError: invalid literal for int() with base 10: ''
2021-06-02 15:54:06,597 - root [INFO] - Using https://ctz.solidwallet.io/api/v3
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/icon-etl/__main__.py", line 25, in <module>
    cli()
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/icon-etl/iconetl/cli/stream.py", line 234, in stream
    pid_file=pid_file,
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 57, in __init__
    self.last_synced_block = read_last_synced_block(self.last_synced_block_file)
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 134, in read_last_synced_block
    return int(last_synced_block_file.read())
ValueError: invalid literal for int() with base 10: ''
2021-06-02 15:54:09,020 - root [INFO] - Using https://ctz.solidwallet.io/api/v3
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/icon-etl/__main__.py", line 25, in <module>
    cli()
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/icon-etl/iconetl/cli/stream.py", line 234, in stream
    pid_file=pid_file,
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 57, in __init__
    self.last_synced_block = read_last_synced_block(self.last_synced_block_file)
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 134, in read_last_synced_block
    return int(last_synced_block_file.read())
ValueError: invalid literal for int() with base 10: ''
2021-06-02 15:54:11,625 - root [INFO] - Using https://ctz.solidwallet.io/api/v3
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/icon-etl/__main__.py", line 25, in <module>
    cli()
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/icon-etl/iconetl/cli/stream.py", line 234, in stream
    pid_file=pid_file,
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 57, in __init__
    self.last_synced_block = read_last_synced_block(self.last_synced_block_file)
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 134, in read_last_synced_block
    return int(last_synced_block_file.read())
ValueError: invalid literal for int() with base 10: ''
2021-06-02 15:54:14,926 - root [INFO] - Using https://ctz.solidwallet.io/api/v3
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/icon-etl/__main__.py", line 25, in <module>
    cli()
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/icon-etl/iconetl/cli/stream.py", line 234, in stream
    pid_file=pid_file,
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 57, in __init__
    self.last_synced_block = read_last_synced_block(self.last_synced_block_file)
  File "/root/.local/lib/python3.6/site-packages/blockchainetl_common/streaming/streamer.py", line 134, in read_last_synced_block
    return int(last_synced_block_file.read())
ValueError: invalid literal for int() with base 10: ''
```

I'm using Docker Desktop for Windows 10 with WSL.

Any suggestions?

Thank you,

**Comment by pranav925** [comment]
### Looks like you did not create the `last_synced_block.txt` volume

The last_synced_block.txt is just a one line file that keeps track of the etl's last synced block. Can start at any block height Looks like this:
```
$ cat ./icon_etl/last_synced_block.txt
35197801
```

This is the docker-compose set up we use regularly:

```
  icon-etl:
    image: geometrylabs/iconetl:${ICON_ETL_TAG:-latest}
    command: [
      "stream",
      "-o", "kafka:9092",
      "--period-seconds", "1",
      "--values-as-hex", "True",
      "-b", "100",
      "-B", "100",
      "-p", "https://ctz.solidwallet.io/api/v3",
    ]
    volumes:
      - "./icon-etl/last_synced_block.txt:/icon-etl/last_synced_block.txt"
    restart: on-failure
```

**Comment by iamacoderguy** [comment]
> ### Looks like you did not create the `last_synced_block.txt` volume
> The last_synced_block.txt is just a one line file that keeps track of the etl's last synced block. Can start at any block height Looks like this:
> 
> ```
> $ cat ./icon_etl/last_synced_block.txt
> 35197801
> ```
> 
> This is the docker-compose set up we use regularly:
> 
> ```
>   icon-etl:
>     image: geometrylabs/iconetl:${ICON_ETL_TAG:-latest}
>     command: [
>       "stream",
>       "-o", "kafka:9092",
>       "--period-seconds", "1",
>       "--values-as-hex", "True",
>       "-b", "100",
>       "-B", "100",
>       "-p", "https://ctz.solidwallet.io/api/v3",
>     ]
>     volumes:
>       - "./icon-etl/last_synced_block.txt:/icon-etl/last_synced_block.txt"
>     restart: on-failure
> ```

I tried to create the last_synced_block.txt file, run the cmd again, and it said icon-etl is not a directory.
If I didn't create a last_synced_block.txt file, docker would create a folder named last_synced_block.txt, then I got another error from icon-etl that last_synced_block.txt is a directory.

Am I understanding you correctly?

![image](https://user-images.githubusercontent.com/53971138/120617899-bcf78f80-c484-11eb-9690-d8b2b0e11e0d.png)

**Comment by pranav925** [comment]
Thats great, closing this issue.

In your screenshot, you need to write a number to the `last_synced_block.txt` file before running it.
